name: babot
dependencies:
- python=3.7
- pip:
  - azure-functions
  - azure-cognitiveservices-speech>=1.5.0
  - edit_distance==1.0.3
  - termcolor
  - matplotlib
  - numpy==1.14.6
  - pandas==0.23.4
  - requests==2.20.1
  - pydub
  - sklearn
  
#python -m ipykernel install --user --name babot --display-name "Python (BA)"
#conda install ipykernel --name babot